### PR TITLE
Update to RobotPy 2023.4.3.0

### PR DESCRIPTION
**Pull request by auscompgeek**
This also pins the RobotPy core libraries to an exact version.

### CODE REVIEW

**Comment by LucienMorey** [comment]
@auscompgeek I will approve this on tuesday after we reflash the rio and make sure its not all broken. If someone sees this running before I do, they can approve it

**Comment by auscompgeek** [comment]
Oh, I figured you were the one that updated the robot. I noticed the imaging tool was open earlier yesterday.

**Comment by LucienMorey** [comment]
I opened the tool and didnt actually get around to doing the update. I will do it on Tuesday.

**Comment by auscompgeek** [comment]
Fair enough. But then who updated RobotPy on the robot then?

**Review by LucienMorey — APPROVED** [review]

**Pull request merged**
