### PR TITLE
Lucien/port chassis

### PR DESCRIPTION
**Pull request by LucienMorey**

### CODE REVIEW

**Comment by LucienMorey** [comment]
FYI, @auscompgeek I removed the line for conditional type checking. I am not sure about what the consequences are for this but when I tried to run the sim it was causing crashes because that var defaults to false and then does not import the robot type. This seems like an error but I am not sure

**Comment by auscompgeek** [comment]
> I am not sure about what the consequences are for this but when I tried to run the sim it was causing crashes because that var defaults to false and then does not import the robot type. This seems like an error but I am not sure

That'd be because the future import was also removed. The type-checking only import is intended to avoid creating two different Robot classes at runtime.

**Comment by auscompgeek** [comment]
> How does that end up happening? I cant see any reason for it at a glance.

robot.py gets run as `__main__` from the command line. Later, `physics` imports `robot`, which doesn't return a reference to the `__main__` module but rather reruns robot.py, giving a different module and Robot class.

> Should it be added back?

Yes, along with the future statement to avoid evaluating the type hint at runtime.

**Comment by LucienMorey** [comment]
> > How does that end up happening? I cant see any reason for it at a glance.
> 
> robot.py gets run as `__main__` from the command line. Later, `physics` imports `robot`, which doesn't return a reference to the `__main__` module but rather reruns robot.py, giving a different module and Robot class.
> 
> > Should it be added back?
> 
> Yes, along with the future statement to avoid evaluating the type hint at runtime.

All fixed. Should be good to go then

**Review by auscompgeek — APPROVED** [review]
Thanks! Given this is basically a straight copy of known working code, LGTM.

**Pull request merged**
